version: '3.8'
services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log debug --user root --pass root memory
    ports:
      - "8000:8000"
    environment:
      SURREAL_LOG: debug